name: dec-rate
channels:
  - conda-forge
dependencies:
  - jupyter-notebook=6.0.3
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ipython=7.12.0
  - python=3.7.6
  - numpy=1.18.1
  - matplotlib=3.1.3
  - ipywidgets=7.5.1
  - appmode=0.7.0
  - jupyterlab>=0.35
  - pip
  - pip:
    - mplhep
    - jupyterlab_latex
